Develop
Mavinxukr/kolgotki.net pull request #3
Opened 2019-12-05 15:04 UTC by Mavinxukr

add sprint 3

2019-12-05 15:40 UTC, a1exalexander requested changes

2019-12-05 15:40 UTC, a1exalexander commented on components/ProfilePageComponents/ProfileFavourite/ProfileFavourite.js
> +      setAmountSelectItems(updateAmountSelectItems);
`setAmountSelectItems(prevState => prevState + 1);`
короче и ясней

2019-12-05 15:40 UTC, a1exalexander commented on components/ProfilePageComponents/ProfileNav/ProfileNav.js
> +          <label onClick={e => setValueForCrumb(e.target.textContent)} className={Styles.ProfileNav__Switcher} htmlFor="data">Мои данные</label>
повторяется код
`const onSetCrumb = (e) => setValueForCrumb(e.target.textContent)`
`<label onClick={onSetCrumb}.....`

2019-12-05 15:40 UTC, a1exalexander commented on components/ProfilePageComponents/ProfileOrderAddInfo/ProfileOrderAddInfo.js
> +        </li>
я бы вынес li в функцию или компонент, не отдельно, а выше в коде
`const Item = ({ label, value }) => {
 return (<li className={Styles.ProfileOrderAddInfo__UserInfoPricesItem}>
          <p className={Styles.ProfileOrderAddInfo__UserInfoPricesText}>{label}</p>
          <p className={Styles.ProfileOrderAddInfo__UserInfoPricesPrice}>{value}</p>
        </li>)
}`

`<Item value={'555 $'} label='Сумма заказа' />`

даже если потом по апи будет приходить массив, легко отмапить

2019-12-09 10:58 UTC, closed without merging

2019-12-09 10:58 UTC, Mavinxukr commented
change project